spring.application.name=CadastroDeNinjas
# Configurações do Banco de Dados H2
spring.datasource.url=jdbc:h2:mem:ninjadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilita o console visual do H2 no navegador para vermos o banco
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Atualiza as tabelas do banco automaticamente quando o projeto inicia
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true